#!/usr/bin/env bash
# E8 EXT-F1 GPU preflight commands -- READ-ONLY ONLY.
#
# Generated by a laptop-side, read-only preflight task. This script performs
# NO training, NO file copy, NO checkpoint creation, NO target access, NO
# destructive git operation, and NO `rm`. It is meant to be run manually, in
# sections, by a human on the GPU host -- it is NOT auto-executed by anything
# in this repository, and this generation task did not run it either.
#
# Required exact commit for every check below:
#   9fb4e2fc7d30ad940e42999524f0d09b81bbf0e5
#
# "latest branch" or "working tree looks equivalent" is NEVER an acceptable
# substitute for this exact commit.

set -euo pipefail

REPO_DIR="/home/sparc/workdir/longnm/PRISM_FAS_C_LLM_Project"
BRANCH="gpu-work/e7-gpat-bank-prep"
REQUIRED_COMMIT="9fb4e2fc7d30ad940e42999524f0d09b81bbf0e5"

echo "=== 1. GPU repository identity (expected HEAD: ${REQUIRED_COMMIT}) ==="
cd "${REPO_DIR}"
git fetch origin
git checkout "${BRANCH}"
git pull --ff-only origin "${BRANCH}"
git rev-parse HEAD
echo "expected: ${REQUIRED_COMMIT}"

echo
echo "=== 2. Python / PyTorch / CUDA environment (read-only) ==="
cd "${REPO_DIR}"
source .venv/bin/activate
export PYTHONPATH="$PWD/src${PYTHONPATH:+:$PYTHONPATH}"
export PRISM_MODEL_CACHE="$PWD/weights"
python --version
python -c "import torch; print('torch', torch.__version__)"
python -c "import torch; print('torch cuda version', torch.version.cuda)"
python -c "import torch; print('cuda available', torch.cuda.is_available())"
python -c "import torch; print('gpu name', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A')"
python -c "import torch; print('gpu count', torch.cuda.device_count())"

echo
echo "=== 3. SigLIP2 model-weight preflight (read-only; file-level SHA256) ==="
python - <<'PYEOF'
import sys
sys.path.insert(0, "src")
from pathlib import Path
from prism_fas.detector.pretrained import SigLIP2Artifacts, SIGLIP2_PIN
weight_root = Path("weights")
print("expected model_id:", SIGLIP2_PIN["model_id"])
print("expected revision:", SIGLIP2_PIN["revision"])
try:
    artifacts = SigLIP2Artifacts.resolve(weight_root, verify=True)
    print("RESOLVED at:", artifacts.root)
    for name, digest in sorted(artifacts.digests.items()):
        print(f"  {name}: {digest}")
except Exception as exc:
    print("NOT RESOLVED / VERIFICATION FAILED (read-only check, no download attempted):", exc)
PYEOF

echo
echo "=== 4. EXT-F1 source_train/source_dev manifest preflight (read-only) ==="
python - <<'PYEOF'
import sys
sys.path.insert(0, "src")
from pathlib import Path
PACKAGE_ROOT = Path("data/processed/c_ext_q1q2_v1/e7_gpat_bank/gpat_input/EXT-F1")
for name in ("source_train.parquet", "source_dev.parquet"):
    path = PACKAGE_ROOT / "manifests" / name
    print(name, "present:", path.is_file(), "at", path)
PYEOF

echo
echo "=== 5. Historical C6 bank-lock hash verification (read-only; NO rewrite) ==="
python - <<'PYEOF'
import sys, hashlib
sys.path.insert(0, "src")
from pathlib import Path
expected = {
    "RND": "451964130e59a084470edfac754dc097658b678d4a4f0811ba964c2cfbbe7d92",
    "DET": "bacd544d7d25e411592262c80f092099ba16e5abaa442b00ebe5514eac79b96d",
    "LLM": "ff57043ac3b2aa1591e630b48fb76e588e7fb3ce39a4894093750c01c5c0893a",
}
for arm, exp in expected.items():
    p = Path(f"reports/full/c6/C6_BANK_LOCK_{arm}.json")
    actual = hashlib.sha256(p.read_bytes()).hexdigest() if p.is_file() else None
    print(arm, "match:", actual == exp, "actual:", actual)
PYEOF

echo
echo "=== 6. E8 membership + adapter integrity (read-only) ==="
python - <<'PYEOF'
import sys
sys.path.insert(0, "src")
from prism_fas.evaluation import c_ext_e8_training_adapter as adapter
for arm in adapter.ARMS:
    b = adapter.resolve_arm_binding(arm)
    print(arm, "membership=", b.membership_count, "physics=", b.physics_count, "gpat=", b.gpat_count)
print("adapter_rule_identity:", adapter.adapter_rule_identity())
print("expected:            56e649a49ba03febbadce6fc62d4362be753d95ccd0fce03d1886f8c5384bbdb")
PYEOF

echo
echo "=== 7. Synthetic pixel-asset presence verification (read-only; per arm) ==="
echo "NOTE: fill in the real candidates_root/recipes/package_identity/recipe_bank_identity"
echo "for this GPU host before running -- template only, no execution here."
python - <<'PYEOF'
import sys
sys.path.insert(0, "src")
from pathlib import Path
from prism_fas.evaluation import c_ext_e8_training_adapter as adapter
from prism_fas.detector.c6_bank import C6BankError

# TEMPLATE -- adjust candidates_root / recipes / package_identity / recipe_bank_identity
# to this GPU host's real C5 candidate tree and C3 recipe bank before running.
#
# for arm in adapter.ARMS:
#     try:
#         reader = adapter.open_e8_arm_bank(
#             arm, candidates_root=Path("<GPU C5 candidate tree>"),
#             recipes=[...load arm's C3 recipe bank...],
#             package_identity="<flow-1 package identity>",
#             recipe_bank_identity="<flow-1 recipe bank identity>")
#         resolved = len(reader)
#         missing = 818 - resolved
#         print(arm, "resolved=", resolved, "missing_payload=", missing)
#     except C6BankError as exc:
#         print(arm, "BLOCKED_E8_GPU_ASSET_MISSING:", exc)
print("template only -- see comment block above; not executed by this preflight")
PYEOF

echo
echo "=== 8. Disk / storage read-only report ==="
df -h
echo "--- du -sh (repo) ---"
du -sh "${REPO_DIR}" 2>/dev/null || true
echo "--- du -sh (weights) ---"
du -sh "${REPO_DIR}/weights" 2>/dev/null || true
echo "--- du -sh (source data package root) ---"
du -sh "${REPO_DIR}/data/processed/c_ext_q1q2_v1/e7_gpat_bank/gpat_input/EXT-F1" 2>/dev/null || true
echo "--- du -sh (historical C6/C5 synthetic payload location) ---"
du -sh "${REPO_DIR}/runs/full/c5" 2>/dev/null || true
echo "--- du -sh (future E8 run-root, if it exists yet) ---"
du -sh "${REPO_DIR}/runs/c_ext_q1q2_v1/e8_qmatched" 2>/dev/null || echo "not yet created"

echo
echo "=== PREFLIGHT COMPLETE (read-only). No training, no copy, no target access performed. ==="
